// <auto-generated />
using BE.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BE.Migrations
{
    [DbContext(typeof(MyAppDBContext))]
    [Migration("20250601130659_Add_TB_Course")]
    partial class Add_TB_Course
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BE.Data.Entities.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(6)
                        .HasColumnType("Char(6)");

                    b.Property<string>("AccountTypeId")
                        .IsRequired()
                        .HasColumnType("Char(6)");

                    b.Property<string>("Avatar")
                        .HasMaxLength(3000)
                        .HasColumnType("VarChar(3000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("VarChar(60)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(20)
                        .HasColumnType("NVarChar(20)");

                    b.Property<string>("LastMiddleName")
                        .HasMaxLength(40)
                        .HasColumnType("NVarChar(40)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("VarChar(25)");

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("BE.Data.Entities.AccountType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(6)
                        .HasColumnType("Char(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVarChar(20)");

                    b.HasKey("Id");

                    b.ToTable("AccountType");
                });

            modelBuilder.Entity("BE.Data.Entities.Course", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(6)
                        .HasColumnType("Char(6)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("VarChar(3000)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("NVarChar(100)");

                    b.Property<string>("HostId")
                        .HasColumnType("Char(6)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("Bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVarChar(20)");

                    b.HasKey("Id");

                    b.HasIndex("HostId");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("BE.Data.Entities.Account", b =>
                {
                    b.HasOne("BE.Data.Entities.AccountType", "OAccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OAccountType");
                });

            modelBuilder.Entity("BE.Data.Entities.Course", b =>
                {
                    b.HasOne("BE.Data.Entities.Account", "OHost")
                        .WithMany("LOwnCourses")
                        .HasForeignKey("HostId");

                    b.Navigation("OHost");
                });

            modelBuilder.Entity("BE.Data.Entities.Account", b =>
                {
                    b.Navigation("LOwnCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
